### ISSUE TITLE
Feature: Event Id Page

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/Zenbit-Badges#1]
- [x] [Create Event Id Branch
](https://github.com/zenbitETH/Zenbit-Badges/tree/Feat/-Event-Id-Page)
- [x] Event details UI
- [x] Event Table UI

**Comment by Markkos89** [comment]
- [x] Fetch Event details based on eventId from the query params
- [x] Fetch the event details using scaffold-eth repository hooks
- [x] Fetch events of the event contract to be listed in the Table

**Comment by HabacucMX** [comment]
Closed in https://github.com/zenbitETH/Zenbit-Badges/pull/4
