### ISSUE TITLE
Feat/ Badge Type 4: Live Event / Workshop

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/Zenbit-Badges#17]
We will add a new `Badge Type` for live events or workshops. It will use a single new `EAS schema` for both Badge variants, where `1. Live Event` requires a secret word revealed during the live event while `2. Workshop` requires answering a 3-option Quiz with questions related to the workshop content.

- [x] Define fields and create Live Event / Workshop Schema in EAS
- [x] Add Live Event Schema (Single Answer Quiz) to `Create Event` form 
- [x] Add Workshop(3-Question Quiz) schema variant to `Create Event` form
- [x] Test on localhost #19 
- [x] #37

**Comment by shyam-patel-kira** [comment]
This is resolved
