### ISSUE TITLE
Type 3 events only works for ENS address in the link post

### ISSUE THREAD

**Issue by shyam-patel-kira** [zenbitETH/Zenbit-Badges#8]
- Need to add support for address multisig as well

- [x] #22

**Comment by shyam-patel-kira** [comment]
ToDOs: 

- [x] schema for this type
- [x] parse the ENS domain from the author sub-domain
- [x] grant attestation based on the membership of that

**Comment by HabacucMX** [comment]
[Base Sepolia Schema 410: DAO Incubation
](https://base-sepolia.easscan.org/schema/view/0x17ceae0972a7b2a858182fa4fc4f63b020941f4386872a2d3b611f882bcdf9bf)

[OP Mainnet Schema 512: DAO Incubation](https://optimism.easscan.org/schema/view/0x17ceae0972a7b2a858182fa4fc4f63b020941f4386872a2d3b611f882bcdf9bf)

**Comment by HabacucMX** [comment]
this needs review on https://github.com/zenbitETH/Zenbit-Badges/pull/29 and working on preview to be closed

**Comment by shyam-patel-kira** [comment]
This works!
